# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import revije_pb2 as revije__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in revije_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RevijeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRevija = channel.unary_unary(
                '/revije.RevijeService/CreateRevija',
                request_serializer=revije__pb2.CreateRevijaRequest.SerializeToString,
                response_deserializer=revije__pb2.Revija.FromString,
                _registered_method=True)
        self.GetRevija = channel.unary_unary(
                '/revije.RevijeService/GetRevija',
                request_serializer=revije__pb2.GetRevijaRequest.SerializeToString,
                response_deserializer=revije__pb2.Revija.FromString,
                _registered_method=True)
        self.UpdateRevija = channel.unary_unary(
                '/revije.RevijeService/UpdateRevija',
                request_serializer=revije__pb2.UpdateRevijaRequest.SerializeToString,
                response_deserializer=revije__pb2.Revija.FromString,
                _registered_method=True)
        self.DeleteRevija = channel.unary_unary(
                '/revije.RevijeService/DeleteRevija',
                request_serializer=revije__pb2.DeleteRevijaRequest.SerializeToString,
                response_deserializer=revije__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListRevije = channel.unary_unary(
                '/revije.RevijeService/ListRevije',
                request_serializer=revije__pb2.ListRevijeRequest.SerializeToString,
                response_deserializer=revije__pb2.ListRevijeResponse.FromString,
                _registered_method=True)


class RevijeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRevija(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevija(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRevija(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRevija(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRevije(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RevijeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRevija': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRevija,
                    request_deserializer=revije__pb2.CreateRevijaRequest.FromString,
                    response_serializer=revije__pb2.Revija.SerializeToString,
            ),
            'GetRevija': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevija,
                    request_deserializer=revije__pb2.GetRevijaRequest.FromString,
                    response_serializer=revije__pb2.Revija.SerializeToString,
            ),
            'UpdateRevija': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRevija,
                    request_deserializer=revije__pb2.UpdateRevijaRequest.FromString,
                    response_serializer=revije__pb2.Revija.SerializeToString,
            ),
            'DeleteRevija': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRevija,
                    request_deserializer=revije__pb2.DeleteRevijaRequest.FromString,
                    response_serializer=revije__pb2.DeleteResponse.SerializeToString,
            ),
            'ListRevije': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRevije,
                    request_deserializer=revije__pb2.ListRevijeRequest.FromString,
                    response_serializer=revije__pb2.ListRevijeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'revije.RevijeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('revije.RevijeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RevijeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRevija(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revije.RevijeService/CreateRevija',
            revije__pb2.CreateRevijaRequest.SerializeToString,
            revije__pb2.Revija.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevija(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revije.RevijeService/GetRevija',
            revije__pb2.GetRevijaRequest.SerializeToString,
            revije__pb2.Revija.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRevija(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revije.RevijeService/UpdateRevija',
            revije__pb2.UpdateRevijaRequest.SerializeToString,
            revije__pb2.Revija.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRevija(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revije.RevijeService/DeleteRevija',
            revije__pb2.DeleteRevijaRequest.SerializeToString,
            revije__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRevije(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revije.RevijeService/ListRevije',
            revije__pb2.ListRevijeRequest.SerializeToString,
            revije__pb2.ListRevijeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
