version: '3'
services:
  revije:
    build: .
    ports:
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb+srv://eriklasic:j0LivIehDD0I38pZ@revije.y2asa.mongodb.net/revije?retryWrites=true&w=majority&appName=revije
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - revije_db:/data/db

volumes:
  revije_db:
