// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: revije.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Revija struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Naslov        string                 `protobuf:"bytes,2,opt,name=naslov,proto3" json:"naslov,omitempty"`
	Avtor         string                 `protobuf:"bytes,3,opt,name=avtor,proto3" json:"avtor,omitempty"`
	LetoIzdaje    int32                  `protobuf:"varint,4,opt,name=leto_izdaje,json=letoIzdaje,proto3" json:"leto_izdaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revija) Reset() {
	*x = Revija{}
	mi := &file_revije_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revija) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revija) ProtoMessage() {}

func (x *Revija) ProtoReflect() protoreflect.Message {
	mi := &file_revije_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revija.ProtoReflect.Descriptor instead.
func (*Revija) Descriptor() ([]byte, []int) {
	return file_revije_proto_rawDescGZIP(), []int{0}
}

func (x *Revija) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Revija) GetNaslov() string {
	if x != nil {
		return x.Naslov
	}
	return ""
}

func (x *Revija) GetAvtor() string {
	if x != nil {
		return x.Avtor
	}
	return ""
}

func (x *Revija) GetLetoIzdaje() int32 {
	if x != nil {
		return x.LetoIzdaje
	}
	return 0
}

type RevijaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevijaRequest) Reset() {
	*x = RevijaRequest{}
	mi := &file_revije_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevijaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevijaRequest) ProtoMessage() {}

func (x *RevijaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revije_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevijaRequest.ProtoReflect.Descriptor instead.
func (*RevijaRequest) Descriptor() ([]byte, []int) {
	return file_revije_proto_rawDescGZIP(), []int{1}
}

func (x *RevijaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_revije_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_revije_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_revije_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_revije_proto protoreflect.FileDescriptor

var file_revije_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x72, 0x65, 0x76, 0x69, 0x6a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x72, 0x65, 0x76, 0x69, 0x6a, 0x65, 0x22, 0x67, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x69, 0x6a, 0x61,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x73, 0x6c, 0x6f, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x61, 0x73, 0x6c, 0x6f, 0x76, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x76, 0x74, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x76, 0x74, 0x6f, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x65, 0x74, 0x6f, 0x5f, 0x69, 0x7a, 0x64, 0x61, 0x6a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x65, 0x74, 0x6f, 0x49, 0x7a, 0x64, 0x61, 0x6a, 0x65, 0x22,
	0x1f, 0x0a, 0x0d, 0x52, 0x65, 0x76, 0x69, 0x6a, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb2, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x76, 0x69, 0x6a,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x44, 0x6f, 0x64, 0x61,
	0x6a, 0x52, 0x65, 0x76, 0x69, 0x6a, 0x6f, 0x12, 0x0e, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x6a, 0x65,
	0x2e, 0x52, 0x65, 0x76, 0x69, 0x6a, 0x61, 0x1a, 0x10, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x6a, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x50, 0x72, 0x69,
	0x64, 0x6f, 0x62, 0x69, 0x52, 0x65, 0x76, 0x69, 0x6a, 0x6f, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x76,
	0x69, 0x6a, 0x65, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x6a, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x6a, 0x65, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x6a,
	0x61, 0x12, 0x38, 0x0a, 0x0d, 0x49, 0x7a, 0x62, 0x72, 0x69, 0x73, 0x69, 0x52, 0x65, 0x76, 0x69,
	0x6a, 0x6f, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x6a, 0x65, 0x2e, 0x52, 0x65, 0x76, 0x69,
	0x6a, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x72, 0x65, 0x76, 0x69,
	0x6a, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x47, 0x5a, 0x45, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x72, 0x69, 0x6b, 0x4c, 0x61,
	0x73, 0x69, 0x63, 0x2f, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x6a, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_revije_proto_rawDescOnce sync.Once
	file_revije_proto_rawDescData []byte
)

func file_revije_proto_rawDescGZIP() []byte {
	file_revije_proto_rawDescOnce.Do(func() {
		file_revije_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revije_proto_rawDesc), len(file_revije_proto_rawDesc)))
	})
	return file_revije_proto_rawDescData
}

var file_revije_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_revije_proto_goTypes = []any{
	(*Revija)(nil),        // 0: revije.Revija
	(*RevijaRequest)(nil), // 1: revije.RevijaRequest
	(*Response)(nil),      // 2: revije.Response
}
var file_revije_proto_depIdxs = []int32{
	0, // 0: revije.RevijeService.DodajRevijo:input_type -> revije.Revija
	1, // 1: revije.RevijeService.PridobiRevijo:input_type -> revije.RevijaRequest
	1, // 2: revije.RevijeService.IzbrisiRevijo:input_type -> revije.RevijaRequest
	2, // 3: revije.RevijeService.DodajRevijo:output_type -> revije.Response
	0, // 4: revije.RevijeService.PridobiRevijo:output_type -> revije.Revija
	2, // 5: revije.RevijeService.IzbrisiRevijo:output_type -> revije.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_revije_proto_init() }
func file_revije_proto_init() {
	if File_revije_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revije_proto_rawDesc), len(file_revije_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revije_proto_goTypes,
		DependencyIndexes: file_revije_proto_depIdxs,
		MessageInfos:      file_revije_proto_msgTypes,
	}.Build()
	File_revije_proto = out.File
	file_revije_proto_goTypes = nil
	file_revije_proto_depIdxs = nil
}
