name: CI/CD Pipeline for Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use temurin for the JDK distribution

      # Step 3: Cache Maven dependencies to speed up builds (optional)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Verify the files and location of pom.xml
      - name: List files to check for pom.xml
        run: |
          ls -R
          
      # Step 5: Navigate to the project directory where pom.xml is located
      - name: Navigate to project directory
        run: |
          cd services/narocnine/narocnine-service
          # List files to ensure pom.xml is present
          ls

      # Step 6: Build the application using Maven
      - name: Build with Maven
        run: |
          cd services/narocnine/narocnine-service
          mvn clean install -DskipTests

      # Step 7: Run tests
      - name: Run tests
        run: mvn test

      # Step 8: Build Docker image (optional, if you want to containerize your app)
      - name: Build Docker image
        run: |
          # Ensure Dockerfile is present in the root directory or adjust path
          docker build -t my-springboot-app .

      # Step 9: Push Docker image to DockerHub (optional)
      - name: Push Docker image to DockerHub (optional)
        if: success()
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag my-springboot-app:latest myusername/my-springboot-app:latest
          docker push myusername/my-springboot-app:latest

      # Step 10: Deploy Application (optional)
      - name: Deploy Application (optional)
        run: |
          echo "Deploying the application..."
          # Add your deployment commands here
