name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Build Docker image
      run: docker build -t narocnine-service .

    - name: Run tests with Maven
      run: mvn test

    - name: Push Docker image to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag narocnine-service:latest your-dockerhub-username/narocnine-service:latest
        docker push your-dockerhub-username/narocnine-service:latest

    - name: Deploy to Docker Compose (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose -f docker-compose.yml up -d
