name: Flask Microservice CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Correct Python version

      - name: Install dependencies
        run: |
          cd uporabniki  # Change to the 'uporabniki' directory
          python -m venv venv  # Create a new virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies from 'requirements.txt'

      - name: Run tests
        run: |
          cd uporabniki  # Change to the 'uporabniki' directory
          source venv/bin/activate  # Activate the virtual environment
          pytest test_app.py  # Run tests from 'test_app.py' in 'uporabniki'
