name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        options: --health-cmd="curl --silent --fail http://localhost:27017" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 27017:27017

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./services/revije  # Nastavi delovno mapo na services/revije

      - name: Run unit tests
        run: npx jest
        working-directory: ./services/revije  # Nastavi delovno mapo na services/revije
